package com.agroinnova.farmerbusinessschool.utils

object Constants{
//    constants common to more tables
    const val DATABASENAME ="fbs"
    const val KEY_ID = "id"
    const val DATABASEVERSION = 3
    const val ITEMNAME ="item_name"
    const val QUANTITY = "quantity"
    const val UNITPRICE ="unit_price"
    const val TOTALPRICE = "total_price"
    const val DATEADDED ="date_added"
    const val USER ="farmerNumber"

    const val TBL_FARMER = "farmers"
    const val FARMERNAME = "farmerName"
    const val PHONENUMBER = "phoneNumber"
    const val PINCODE = "pinCode"

    //   has item name
    const val TBL_MONEY_IN_ITEMS ="money_in_items"

    //    has item name
    const val TBL_NEW_MONEY_IN="new_money_in"



    fun countries(): Array<String> {
        return arrayOf(
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antigua & Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bosnia & Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei Darussalam",
            "Bulgaria",
            "Burkina Faso",
            "Myanmar/Burma",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Cayman Islands",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Democratic Republic of the Congo",
            "Denmark",
            "Djibouti",
            "Dominican Republic",
            "Dominica",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "French Guiana",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Great Britain",
            "Greece",
            "Grenada",
            "Guadeloupe",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Israel and the Occupied Territories",
            "Italy",
            "Ivory Coast (Cote d'Ivoire)",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kosovo",
            "Kuwait",
            "Kyrgyz Republic (Kyrgyzstan)",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Republic of Macedonia",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Mexico",
            "Moldova, Republic of Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Namibia",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Korea, Democratic Republic of (North Korea)",
            "Norway",
            "Oman",
            "Pacific Islands",
            "Pakistan",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Reunion",
            "Romania",
            "Russian Federation",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent's & Grenadines",
            "Samoa",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovak Republic ",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "Korea, Republic of (South Korea)",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syria",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Timor Leste",
            "Togo",
            "Trinidad & Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks & Caicos Islands",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United States of America (USA)",
            "Uruguay",
            "Uzbekistan",
            "Venezuela",
            "Vietnam",
            "Virgin Islands (UK)",
            "Virgin Islands (US)",
            "Yemen",
            "Zambia",
            "Zimbabwe"
        )
    }
    fun ashanti(): Array<String> {
        return arrayOf(
            "Adansi North District",
            "Adansi South District",
            "Afigya-Kwabre District",
            "Ahafo Ano North District",
            "Ahafo Ano South District",
            "Amansie Central District",
            "Amansie West District",
            "Asante Akim Central Municipal District",
            "Asante Akim North District",
            "Asante Akim South District",
            "Asokore Mampong Municipal District",
            "Atwima Kwanwoma District",
            "Atwima Mponua District",
            "Atwima Nwabiagya District",
            "Bekwai Municipal District",
            "Bosome Freho District",
            "Botsomtwe District",
            "Ejisu-Juaben Municipal District",
            "Ejura - Sekyedumase District",
            "Kumasi Metropolitan District",
            "Kwabre East District",
            "Mampong Municipal District",
            "Obuasi Municipal District",
            "Offinso North District",
            "Offinso South Municipal District",
            "Sekyere Afram Plains District",
            "Sekyere Central District",
            "Sekyere East District",
            "Sekyere Kumawu District",
            "Sekyere South District"
        )
    }

    fun brongAhafo(): Array<String> {
        return arrayOf(
            "Asunafo North Municipal District",
            "Asunafo South District",
            "Asutifi North District",
            "Asutifi South District",
            "Atebubu-Amantin District",
            "Banda District",
            "Berekum East Municipal District",
            "Berekum Municipal District",
            "Dormaa East District",
            "Dormaa Municipal District",
            "Dormaa West District",
            "Jaman North District",
            "Jaman South District",
            "Kintampo North Municipal District",
            "Kintampo South District",
            "Nkoranza North District",
            "Nkoranza South District",
            "Pru District",
            "Sene East District",
            "Sene West District",
            "Sunyani Municipal District",
            "Sunyani West District",
            "Tain District",
            "Tano North District",
            "Tano South District",
            "Techiman Municipal District",
            "Techiman North District",
            "Wenchi Municipal District"
        )
    }

    fun greaterAccra(): Array<String> {
        return arrayOf(
            "Ablekuma North Municipal District",
            "Ablekuma West Municipal District",
            "Accra Metropolitan District",
            "Ada East District",
            "Ada West District",
            "Adenta Municipal District",
            "Ashaiman Municipal District",
            "Ayawaso East Municipal District",
            "Ayawaso North Municipal District",
            "Ayawaso West Municipal District",
            "Ga Central District",
            "Ga East Municipal District",
            "Ga North Municipal District",
            "Ga South Municipal District",
            "Ga West Municipal District",
            "Kpone Katamanso Municipal District",
            "Krowor Municipal District",
            "La Dade Kotopon Municipal District",
            "La Nkwantanang Madina Municipal District",
            "Ledzokuku Municipal District",
            "Ningo Prampram District",
            "Okaikwei Municipal District",
            "Shai Osudoku District",
            "Tema Metropolitan District",
            "Tema West Municipal District",
            "Weija Municipal District"
        )
    }

    fun central(): Array<String> {
        return arrayOf(
            "Abura/Asebu/Kwamankese District",
            "Agona East District",
            "Agona West Municipal District",
            "Ajumako/Enyan/Essiam District",
            "Asikuma/Odoben/Brakwa District",
            "Assin North Municipal District",
            "Assin South District",
            "Awutu Senya East Municipal District",
            "Awutu Senya West District",
            "Cape Coast Metropolitan District",
            "Effutu Municipal District",
            "Ekumfi District",
            "Gomoa East District",
            "Gomoa West District",
            "Komenda/Edina/Eguafo/Abirem Municipal District",
            "Mfantsiman Municipal District",
            "Twifo-Ati Morkwa District",
            "Twifo/Heman/Lower Denkyira District",
            "Upper Denkyira East Municipal District",
            "Upper Denkyira West District"
        )
    }

    fun eastern(): Array<String> {
        return arrayOf(
            "Akuapim South District",
            "Akuapim North District",
            "Akyemansa District",
            "Asuogyaman District",
            "Ayensuano District",
            "Atiwa District",
            "Birim Central Municipal District",
            "Birim North District",
            "Birim South District",
            "Denkyembour District",
            "East Akim Municipal District",
            "Fanteakwa District",
            "Kwaebibirem District",
            "Kwahu Afram Plains North District",
            "Kwahu Afram Plains South District",
            "Kwahu East District",
            "Kwahu South District",
            "Kwahu West Municipal District",
            "Lower Manya Krobo District",
            "New-Juaben Municipal District",
            "Nsawam Adoagyire Municipal District",
            "Suhum Municipal",
            "Upper Manya Krobo District",
            "Upper West Akim District",
            "West Akim Municipal District",
            "Yilo Krobo Municipal"
        )
    }

    fun northern(): Array<String> {
        return arrayOf(
            "Bole District",
            "Bunkpurugu-Yunyoo District",
            "Central Gonja District",
            "Chereponi District",
            "East Gonja District",
            "East Mamprusi District",
            "Gushegu District",
            "Karaga District",
            "Kpandai District",
            "Kumbungu District",
            "Mamprugo Moaduri District",
            "Mion District",
            "Nanton District",
            "Nanumba North District",
            "Nanumba South District",
            "North Gonja District",
            "Saboba District",
            "Sagnarigu District",
            "Savelugu Municipal District",
            "Sawla-Tuna-Kalba District",
            "Tamale Metropolitan District",
            "Tatale Sangule District",
            "Tolon District",
            "West Gonja District",
            "West Mamprusi District",
            "Yendi Municipal District",
            "Zabzugu District"
        )
    }

    fun upperEast(): Array<String> {
        return arrayOf(
            "Bawku Municipal District",
            "Bawku West District",
            "Binduri District",
            "Bolgatanga Municipal District",
            "Bongo District",
            "Builsa District",
            "Builsa South District",
            "Garu-Tempane District",
            "Kassena Nankana East District",
            "Kassena Nankana West District",
            "Nabdam District",
            "Pusiga District",
            "Talensi District"
        )
    }

    fun upperWest(): Array<String> {
        return arrayOf(
            "Daffiama Bussie Issa District",
            "Jirapa District",
            "Lambussie Karni District",
            "Lawra District",
            "Nadowli District",
            "Nandom District",
            "Sissala East District",
            "Sissala West District",
            "Wa East District",
            "Wa Municipal District",
            "Wa West District"
        )
    }

    fun volta(): Array<String> {
        return arrayOf(
            "Adaklu District",
            "Afadjato South District",
            "Agotime Ziope District",
            "Akatsi North District",
            "Akatsi South District",
            "Biakoye District",
            "Central Tongu District",
            "Ho Municipal District",
            "Ho West District",
            "Hohoe Municipal District",
            "Jasikan District",
            "Kadjebi District",
            "Keta Municipal District",
            "Ketu North District",
            "Ketu South Municipal District",
            "Kpando Municipal District",
            "Krachi East District",
            "Krachi Nchumuru District",
            "Krachi West District",
            "Nkwanta North District",
            "Nkwanta South District",
            "North Dayi District",
            "North Tongu District",
            "South Dayi District",
            "South Tongu District"
        )
    }

    fun western(): Array<String> {
        return arrayOf(
            "Ahanta West District",
            "Aowin/Suaman District",
            "Bia West District",
            "Bia East District",
            "Bibiani/Anhwiaso/Bekwai District",
            "Bodi District",
            "Ellembele District",
            "Jomoro District",
            "Juaboso District",
            "Mpohor District",
            "Mpohor/Wassa East District",
            "Nzema East Municipal District",
            "Prestea-Huni Valley District",
            "Sefwi Akontombra District",
            "Sefwi Wiawso Municipal District",
            "Sekondi Takoradi Metropolitan Assembly",
            "Shama District",
            "Suaman District",
            "Tarkwa-Nsuaem Municipal District",
            "Wasa Amenfi East District",
            "Wasa Amenfi West District",
            "Wassa Amenfi Central District"
        )
    }

}